name: flutter_todos
description: A new Flutter project.

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  equatable: ^1.1.1
  intl: ^0.16.1
  path_provider: ^1.6.10
  bloc: ^4.0.0
  flutter_bloc: ^4.0.0
  rxdart: ^0.23.1
  key_value_store: ^1.0.0
  #  flutter_bloc:
  #  path: ../../packages/flutter_bloc
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.1
  intl_translation: ^0.17.10


#dependency_overrides:
#  todos_app_core:
#    git:
#      url: https://github.com/felangel/flutter_architecture_samples
#      path: todos_app_core
#      ref: rxdart/0.23.0
#  todos_repository_core:
#    git:
#      url: https://github.com/felangel/flutter_architecture_samples
#      path: todos_repository_core
#      ref: rxdart/0.23.0
#  todos_repository_simple:
#    git:
#      url: https://github.com/felangel/flutter_architecture_samples
#      path: todos_repository_simple
#      ref: rxdart/0.23.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/